<a href="https://colab.research.google.com/github/Nikolai-N484/Data201_NikolaiN/blob/main/Data201_Class1_Student_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Class 1 – Python Foundations (Student Notebook)

Bridge goal: translate familiar R patterns into Python.

Class 1 (Student Version): Python Fundamentals for R Users
Course: Intro to Data Analysis in Python
Background assumed: R, linear/logistic regression, basic ggplot2


=====================================================
 HOW TO USE THIS NOTEBOOK
=====================================================
 - Run cells top to bottom
 - Read the comments carefully
 - Complete all TODO sections
 - Predict outputs BEFORE running when prompted

=====================================================
 0. Setup
 =====================================================

In [ ]:
import numpy as np
import pandas as pd

 =====================================================
 1. First Contact: Python vs R
 =====================================================

 In R:
 x <- c(1, 2, 3)
 mean(x)

 In Python, we must say WHICH library computes the mean.

In [ ]:
x = [1, 2, 3]
mean(x)

NameError: name 'mean' is not defined

**Exercise**
1. Try np.mean(x)
2. What happens if you try mean(x)?

In [ ]:
np.mean(x)

np.float64(2.0)

In [ ]:
#What happens if you try mean(x)?

You get an error message



# 2. Objects, Types, and Explicitness

In [ ]:
x_int = 3
x_float = 3.0
x_bool = True
x_none = None

**Exercise:**
Use type() to check the type of each object above.

In [ ]:
#Type your code here.
type(x_int)
type(x_float)
type(x_bool)
type(x_none)


bool

 **Question:**
Which of these behaves most like NA in R? Which does NOT?

# 3. Core Data Structures

**A. Lists** (similar to flexible R lists)

In [ ]:
L = [1, 2, 3, 4]

**Exercise**
1. Access the first element of L
2. Access the last element of L


Predict before running:
What will L[1:3] return?

In [ ]:
#1.  Access the first element of L
L[0]

1

In [ ]:
#2. Access the last element of L
L[3]

4

In [ ]:
#What will L[1:3] return? It will find L[1],L[2]
L[1:3]

[2, 3]

**B. Tuples** (immutable lists) ---

In [ ]:
T = (1, 2, 3)

**Question:**
Why might immutability be useful?

**C. Dictionaries** (named structures)


In [ ]:
D = {"a": 10, "b": 20, "c": 30}

**Exercise**


In [ ]:
# Extract the value associated with key "b"
D["b"]

20

# 4. Control Flow


In [1]:
x = 5
if x > 0:
  print("positive")
else:
  print("zero or negative")

positive


**A. If/elif/else statements**

**Exercise**
Write an if/elif/else statement that sets:


sign = "positive", "negative", or "zero"

In [2]:
#Write your if/elif/else statement
if x > 0:
  print("positive")
elif x < 0:
  print("negative")
else:
  print("zero")

positive


**B. For loops**

**Exercise**
Use a for-loop to create a list of squares from 0 to 4

In [3]:
#For-loop
[1, 2, 3]*4

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

** C. List comprehension** (Pythonic shortcut)

**Exercise**
Rewrite the previous loop using a list comprehension

In [ ]:
#List comprehension

# 5. NumPy: Vectorized Computation

In [ ]:
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

Predict BEFORE running:
What do you expect x + y to return?


**Exercise**

In [ ]:
# 1. Compute x + y
x + y

array([11, 22, 33, 44])

In [ ]:
# 2. Compute x * y
x * y

array([ 10,  40,  90, 160])

In [ ]:
# 3. Add 5 to every element of x
x + 5

array([6, 7, 8, 9])

In [ ]:
# 4. Compute the mean and standard deviation of x
np.std(x)

np.float64(1.118033988749895)

 Conditional logic (like ifelse in R)

**Exercise**

In [ ]:
# Use np.where to return x when x > 2, and 0 otherwise

# 6. Common Pitfalls for R Users


In [ ]:
L = [1, 2, 3]

Predict:  
What will happen if you try L + 1?


**Exercise**

Try it and explain the result

---



In [ ]:
#Try L + 1

# 7. Active Learning Exercise (15–20 minutes)

 R code:
` x <- c(2, 4, 6, 8)`

` y <- ifelse(x > 4, x / 2, x * 2)`

 `mean(y)`


**TASK:**
1. Translate the code above into Python
2. Predict the value of y BEFORE computing
3. Compute mean(y)


In [ ]:
# Step 1: Create x

In [ ]:
# Step 2: Create y using NumPy

In [ ]:
# Step 3: Compute mean(y)

# 8. Wrap-Up Reflection

In 2–3 sentences:
 - What felt most different from R?
 - What felt familiar?
 - What questions do you still have?